{% set name = "spint" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33fec949d9ac1bb258dac8599f33cd3e9c70af241938fa49312ec8ac7cf116ea

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<312]

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - setuptools_scm >=6.2
    - toml
  run:
    - python
    - libpysal >=4.12
    - numpy >=1.26
    - scipy >=1.12
    - spglm >=1.1
    - spreg >=1.3

test:
  imports:
    - spint
  requires:
    - python
  commands:
    - pip check

about:
  home: https://pysal.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Efficient calibration of spatial interaction models in Python
  description: |
    The Spatial Interaction Modeling (SpInt) module provides a collection of
    tools to study spatial interaction processes and analyze spatial
    interaction data.
  doc_url: https://readthedocs.org/projects/spint
  dev_url: https://github.com/pysal/spint

extra:
  recipe-maintainers:
    - TaylorOshan
