travis:
  secure:
    BINSTAR_TOKEN: CWW8E0BskXLCSsTkZgEPReNvCVkS5HXY4LigkJd2JoH0YJN2QdWJxVccj862lu+vEiU5yeW7kBm4zfJmK3iooknxM5wP57H02t3hinmXFCQsS06ZHV58beeZ3IwRp6w1Y5To9yHsNGXQTnEhvQhufyXWbQR1PMtRh0oTI0vOMGqVAOzVMajO1oHOOGuyakt8/LHfDvnw0hqAEDs2eqgNKkYssj55vR1jaCX64Q41I5mug8gg0oZciwJqMpzwXuOdf9tXP7Twq+nyLw1F1TwhVHjIe129OYq1dLJ2/uPVC99y8IY9uBfbCivVD9DpKr/4lOj0JZVeHC1TCzdAv/Y/RrBLJ3omHzSl2AH33H8daWM1uTQQWu15BsiWQF8Ukh1hIIUtiHS5ISnd5pasxQe/A+dQFB+jcOLHvuh/A2CW6v7DpTeK1qrzKAQgTZkKjs7cswO+8E+OoPoYoO6YDbYNS0RXcCEbEL4jwFurEmKUz3zZDgp3Sq5GLAq/u/5TBDsTP//lOKZ9zheftW9BtfMwhe+nw0sBP6yw/PgeOeYcT4PMI8a/3UKQ8M98Bt8LfLbzT6cjQSD5LT42rG0XUkoG8uHhkKcbrMXYtCdXtAWAc5lqWc/wdNEhiZbxVswS3FU9ilQKdBzzvYNW/Yfmwb2HtIb/b2/77rsLeNsuL7JmieM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
